# Generated by Django 5.1.1 on 2024-10-10 18:31

import accounting.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashBookCPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('cpf', models.CharField(max_length=11)),
                ('yearReference', models.DateField()),
            ],
            options={
                'verbose_name': 'CashBookCPF',
                'unique_together': {('cpf', 'yearReference')},
            },
        ),
        migrations.CreateModel(
            name='CreditRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=250)),
                ('typeOperation', models.CharField(choices=accounting.models.TypeOperation.choices, default=accounting.models.TypeOperation['CREDIT'], max_length=10)),
                ('amount', models.FloatField()),
                ('launchDate', models.DateField()),
                ('costCenter', models.CharField(choices=accounting.models.CostCenter.choices, max_length=50)),
                ('supplier', models.CharField(max_length=50)),
                ('cashBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cashbookcpf', to='accounting.cashbookcpf')),
            ],
            options={
                'verbose_name': 'CreditRegister',
            },
        ),
        migrations.CreateModel(
            name='DebitRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=250)),
                ('typeOperation', models.CharField(choices=accounting.models.TypeOperation.choices, default=accounting.models.TypeOperation['DEBIT'], max_length=10)),
                ('amount', models.FloatField()),
                ('launchDate', models.DateField()),
                ('costCenter', models.CharField(choices=accounting.models.CostCenter.choices, max_length=50)),
                ('supplier', models.CharField(max_length=50)),
                ('cashBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_cashbookcpf', to='accounting.cashbookcpf')),
            ],
            options={
                'verbose_name': 'DebitRegister',
            },
        ),
    ]
